name: Node.js
on: [push] 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
 
        

